### ISSUE TITLE
Default theme is ignored on Google Pro 7 with Chrome when open from SMS the latest P63

### ISSUE THREAD

**Issue by Watvedt** [Cadify/User-Reported-Bugs#1]
In preparation for reqruiting user of the SAKON, I have started testing out inviting by sending SMS link of the SAKON configurator on staging.

I sent this link by SMS to Espen, SAKON configurator on sylinderakutten.ovalas.no
Imre has set default theme = **Mobee**
https://sylinderakutten.ovalas.no/sylinderkonfigurator-250-bar-p63

This has been working perfectly for me when testing Chrome desktop and iphone.

For Espen, on his GooglePro7 phone, the SAKON insist on opening in theme Default = Looks very bad.

Here is a link to a MP4 screenshot video of him opening on his phone:

https://www.dropbox.com/scl/fi/wzxekdd72b2l2c5ph7st6/screen-20241218-074411.mp4?rlkey=yjnznbka0izsowddbwhg8r2le&dl=0

NOTE: On the video Espen is not able to log-in to the staging environment: **All is MY FAULT,** I have not set up and distributed the login for new staging sylinderakutten.ovalas.no yet.

**Comment by szucsim** [comment]
The default theme was not set previously.

I have set it now, so it will no longer be an issue for new users.
For users who have already visited our page, the 'default clean' theme may have been cached. If that's the case, they can use the theme selector at the bottom of the website to change it.

I will close the issue with this comment.
